---
name: create changelog
on:
  workflow_call:
    inputs:
      collection_namespace:
        description: "Install collection python dependencies"
        required: true
        type: string
      collection_name:
        description: "Path to the collection source"
        required: true
        type: string
      collection_version:
        description: The final collection path
        required: false
        type: string
      collection_repo:
        description: The collection url
        required: false
        type: string
    secrets:
      token:
        description: token for uploading tarballs to a release
        required: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core antsibull-changelog

      - name: template galaxy file
        run: ansible all -i 'localhost,' -c local -m template -a "src=galaxy.yml.j2 dest=galaxy.yml" --extra-vars "collection_namespace=${{ inputs.collection_namespace }} collection_name=${{ inputs.collection_name }} collection_version=${{ inputs.collection_version }} collection_repo=${{ inputs.collection_repo }}"
        shell: bash

      - name: Run changelog
        run: antsibull-changelog release --verbose --version ${{ inputs.collection_version }}

      - name: Remove galaxy file
        run: rm galaxy.yml

      - name: Create Pull Request
        id: prcreate
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.token }}
          commit-message: Update changelog ${{ github.ref }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: devel
          branch: changelog-patches
          delete-branch: true
          title: '[RELEASE] Update changelog ${{ github.ref }}'
          body: |
            Update changelog
            - Updated with changelog for release ${{ github.ref }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            changelog
            automated pr
          draft: false
...
