---
name: Update pre-commit
on:
  workflow_call:
    inputs:
      github_actor:
        description: github.actor for the PR
        required: true
        type: string
    secrets:
      token:
        description: github secrets.token
        required: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install pre-commit
        run: pip install --upgrade pre-commit

      - name: Update pre-commit
        run: pre-commit autoupdate

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade "ansible-core>=2.15,<2.19"

      - name: Run Pre-commit to alert of any linting changes.
        continue-on-error: true
        uses: pre-commit/action@v3.0.1

      - name: Remove .ansible folder
        run: rm -rf .ansible

      - name: Create Pull Request
        id: prcreate
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.token }}
          commit-message: Update pre-commit
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/update-pre-commit
          delete-branch: true
          title: 'Update pre-commit'
          body: |
            Update pre-commit
            - Updated pre-commit
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            pre-commit
            automated pr
          draft: false
...
