---
name: Update pre-commit
on:
  workflow_call:
    inputs:
      github_actor:
        description: github.actor for the PR
        required: true
        type: string
    secrets:
      token:
        description: github secrets.token
        required: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3

      - name: Install pre-commit
        run: pip install --upgrade pre-commit

      - name: Update pre-commit
        run: pre-commit autoupdate

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core

      - uses: pre-commit/action@v3.0.0

      - name: Create Pull Request
        id: prcreate
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.token }}
          commit-message: Update pre-commit
          committer: GitHub <noreply@github.com>
          author: ${{ inputs.github_actor }} <${{ inputs.github_actor }}@users.noreply.github.com>
          signoff: false
          base: devel
          branch: pre-commit-update
          delete-branch: true
          title: 'Update pre-commit'
          body: |
            Update pre-commit
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            pre-commit
            automated pr
          draft: false
...
